/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Calendario` | `/Calendario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Equipe` | `/Equipe`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/Formulario`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/FormularioEquipe`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/Home`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/App`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Calendario` | `/Calendario`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Equipe` | `/Equipe`; params?: Router.UnknownOutputParams; } | { pathname: `/Screens/Formulario`; params?: Router.UnknownOutputParams; } | { pathname: `/Screens/FormularioEquipe`; params?: Router.UnknownOutputParams; } | { pathname: `/Screens/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/Screens/Perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/App${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Calendario${`?${string}` | `#${string}` | ''}` | `/Calendario${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Equipe${`?${string}` | `#${string}` | ''}` | `/Equipe${`?${string}` | `#${string}` | ''}` | `/Screens/Formulario${`?${string}` | `#${string}` | ''}` | `/Screens/FormularioEquipe${`?${string}` | `#${string}` | ''}` | `/Screens/Home${`?${string}` | `#${string}` | ''}` | `/Screens/Perfil${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Calendario` | `/Calendario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Equipe` | `/Equipe`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/Formulario`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/FormularioEquipe`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/Home`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/Perfil`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
